### PR TITLE
List Blur (BLUR)

### PR DESCRIPTION
**Pull request by ghost**
- Official project URL: https://blur.cash
- Official block explorer URL: http://explorer.blur.cash

### CODE REVIEW

**Comment by blabno** [comment]
ACK

@cbeams this is privacy coin so please verify if you can do arbitration with it.

**Review by blabno — APPROVED** [review]
ACK

@cbeams this is privacy coin so please verify if you can do arbitration with it.

**Comment by blur-network** [comment]
@blabno @cbeams Arbitration can be easily accomplished with the same methods as Monero.  Output key checking is enabled on the explorer, as well as proving of sent outputs.  All verification would take place with only the viewkey of interested parties.  Spend keys should never be necessary information for arbitration.

**Comment by blur-network** [comment]
@cbeams @blabno Additional: The Blur CLI wallet issues a transaction private key, similar to Monero. Using that key and a recipient address, arbitrators can verify transactions by using the Blur Transaction Viewer (https://blur.cash/#tx-viewer). Two additional pull requests are being submitted for a pop-up explaining the requirements for trading BLUR on Bisq. 

The two other PR's can be found here: 
bisq-network/bisq-desktop/pull/1617
bisq-network/bisq-core/pull/142

**Comment by blur-network** [comment]
Updated branch to include changes since CCX listing, and reissued changes as single commit. Pop-up with information regarding arbitration has been added, and merged.

**Comment by cbeams** [comment]
This repository has been moved into the 'assets' directory of the https://github.com/bisq-network/bisq repository. Please resubmit this pull request against that repository. See https://github.com/bisq-network/bisq-docs/pull/84 for updated instructions. When submitting your pull request, please mention in the description (a) that this is a resubmission, (b) paste a link back to this original pull request, and (c) whether the original had already bee ACKed. Thank you.

**Pull request closed without merging**
