### PR TITLE
List Cryptonodes (CNMC)

### PR DESCRIPTION
**Pull request by ghost**
- Official project URL: https://www.cryptonodes.ch
- Official block explorer URL: http://explorer.cryptonodes.ch

### CODE REVIEW

**Review by cbeams — CHANGES_REQUESTED** [review]
NACK. Amend your commit comment so it reads the way https://docs.bisq.network/exchange/howto/list-asset.html#step-5-create-a-well-formed-git-commit says it should.

Force push the result. Do not create a new PR.

**Comment by cbeams** [comment]
Nevermind my last comment. I accidentally merged this pull request anyway. So it's in now and will ship with v0.7.1.

**Comment by Caberhagen** [comment]
sorry for that and ty.

**Comment by cryptonodes-core** [comment]
sorry for that and ty

**Pull request merged**
