### PR TITLE
List UltraNote (XUN)

### PR DESCRIPTION
**Pull request by UltraNote**
Official project URL: https://ultranote.org
Official block explorer URL: http://explorer.ultranote.org/

### CODE REVIEW

**Comment by blabno** [comment]
This is a privacy coin. How can the arbitration be conducted?

**Review by blabno — CHANGES_REQUESTED** [review]
NACK squash those commits
I've applied bisq codestyle

**Comment by eliottha** [comment]
@blabno I'm a developer at UltraNote, what do you mean with "How can the arbitration be conducted?"

**Comment by eliottha** [comment]
Do you mean this?
http://explorer.ultranote.org/?hash=HASH_COMES_HERE#blockchain_transaction

Also check these two lines : https://github.com/xun-project/UltraNote-Pool/blob/master/website_example/config.js#L9-L10

**Comment by blabno** [comment]
What's the difference between key and image?

**Comment by UltraNote** [comment]
They are same, key is wallet private key and image works as QR for same private key. If that what you ask about.

You can see it in action here:
https://paperwallet.ultranote.org
 Or when you open wallet and click show private key. You will get access to a key and image which can be saved for wallet recovery.

**Comment by blabno** [comment]
So how only the 2 parties that do the trade can see the details?
3rd parties won't see it?

**Comment by UltraNote** [comment]
You can see and check TX details on the explorer but will never know which users sent what to who. Meaning you can't trace a wallet address to a user.

Most exchanges build the walletd and generate a new address for each user or adding a PaymentID for users, and all users use same exchange wallet address but different payment ID.

**Comment by cbeams** [comment]
This repository has been moved into the 'assets' directory of the https://github.com/bisq-network/bisq repository. Please resubmit this pull request against that repository. See https://github.com/bisq-network/bisq-docs/pull/84 for updated instructions. When submitting your pull request, please mention in the description (a) that this is a resubmission, (b) paste a link back to this original pull request, and (c) whether the original had already bee ACKed. Thank you.

**Pull request closed without merging**
