### PR TITLE
List PRiVCY (PRiV)

### PR DESCRIPTION
**Pull request by privcycoin**
* Official project URL: http://privcy.io
* Official block explorer URL: http://explorer.privcy.io/

### CODE REVIEW

**Comment by blabno** [comment]
@cbeams what do you think about PRiVCY class name? I'd go with Privcy.

**Comment by blabno** [comment]
Code looks good.

**Comment by cbeams** [comment]
> @cbeams what do you think about PRiVCY class name? I'd go with Privcy.

As general Java class naming style, `Privcy` would indeed be the way to go, but our convention here in bisq-assets has been to have the class name match precisely the spelling and capitalization of the asset as their promoters refer to it in their materials. Looking around the PRiVCY website, I see that they're quite consistent in that spelling, so let's keep it as-is in the PR. Basically, they've followed that convention, so it's all good.

However, the use of the lowercase 'i' in the ticker symbol `PRiV` is not conventional. I just double-checked, and all asset ticker symbols are upper case, so let's not diverge from that here. If you're happy with the code otherwise, then you can just push an additional commit renaming that ticker symbol. Or @privcycoin you can do the same of course.

Also @blabno, these conventions aren't written down anywhere explicitly other than this comment. Feel free to patch the `list-asset` doc with them if you like.

**Comment by blabno** [comment]
@privcycoin please squash those commits into one (just keep the commit message as in the first one).

**Pull request closed without merging**
