### PR TITLE
List Cryptonodes (CNMC)

### PR DESCRIPTION
**Pull request by cryptonodes-core**
- Official project URL: https://www.cryptonodes.ch
- Official block explorer URL: http://explorer.cryptonodes.ch

### CODE REVIEW

**Comment by cryptonodes-core** [comment]
sorry, make a new one

**Comment by blabno** [comment]
Don't create new pr. Just update the branch.

pt., 22 cze 2018, 19:45 użytkownik cryptonodes-core <
notifications@github.com> napisał:

**Comment by cryptonodes-core** [comment]
how can i change branch after the pull is created?

**Comment by cryptonodes-core** [comment]
the new one is ok from dev branch.
should i reopen new and close this?

**Comment by blabno** [comment]
You can just edit this one

**Comment by cryptonodes-core** [comment]
sorry can only edit target not source.

**Pull request closed without merging**
