### PR TITLE
List Dragonglass (DRGL)

### PR DESCRIPTION
**Pull request by aejontargaryen**
Official project URL: https://zirtysperzys.org
Official block explorer URL: http://zirtysperzys.info
Additional: DRGL wallets support transaction keys that enable 3rd party audits in case of a dispute         similar to Monero

### CODE REVIEW

**Comment by blabno** [comment]
What is this? Dragonglass kills white walkers?

**Comment by aejontargaryen** [comment]
@blabno  :smiley: Yes!!!   http://gameofthrones.wikia.com/wiki/Dragonglass

**Comment by aejontargaryen** [comment]
@blabno  a fan currency! :1st_place_medal:

**Comment by aejontargaryen** [comment]
@blabno  talk to me Bernard. Whats the issue?

**Comment by aejontargaryen** [comment]
let me send you some DRGL @blabno  So you can get an idea of what it is.

**Comment by aejontargaryen** [comment]
"Bisq maintainers merge or reject asset listing pull requests based strictly on the formal requirements laid out in this document, not on any political, legal or ethical grounds. If you follow the instructions, the bisq-assets maintainers will merge it; if you don’t, they won’t. It’s that simple."
https://bisq.network/list-asset

**Comment by blabno** [comment]
There is a discussion going on right now about listing new assets so we're pausing on adding new assets until we get final decision: https://github.com/bisq-network/proposals/issues/35

**Comment by aejontargaryen** [comment]
Ok buddy. Thanks for the info

**Review by blabno — CHANGES_REQUESTED** [review]
NACK `unknown repository`

**Comment by cbeams** [comment]
This repository has been moved into the 'assets' directory of the https://github.com/bisq-network/bisq repository. Please resubmit this pull request against that repository. See https://github.com/bisq-network/bisq-docs/pull/84 for updated instructions. When submitting your pull request, please mention in the description (a) that this is a resubmission, (b) paste a link back to this original pull request, and (c) whether the original had already bee ACKed. Thank you.

**Pull request closed without merging**
