### PR TITLE
List Dero (DERO)

### PR DESCRIPTION
**Pull request by ghost**
Official project URL: http://dero.io
Official block explorer URL: http://explorer.dero.io

### CODE REVIEW

**Review by blabno — CHANGES_REQUESTED** [review]
NACK. Invalid commit message

Squash those commits into single one.

**Comment by owa** [comment]
@blabno it's done.

**Comment by blabno** [comment]
Correct message would be `List Dero (DERO)`

**Comment by owa** [comment]
@blabno sorry about that, I've changed it.

**Review by blabno — APPROVED** [review]
ACK

**Comment by cbeams** [comment]
This repository has been moved into the 'assets' directory of the https://github.com/bisq-network/bisq repository. Please resubmit this pull request against that repository. See https://github.com/bisq-network/bisq-docs/pull/84 for updated instructions. When submitting your pull request, please mention in the description (a) that this is a resubmission, (b) paste a link back to this original pull request, and (c) whether the original had already bee ACKed. Thank you.

**Pull request closed without merging**
