### PR TITLE
List Zero (ZER)

### PR DESCRIPTION
**Pull request by tearodactyl**
- Official project URL: https://zerocurrency.io/
- Official block explorer URL: https://zeroexplorer.prophetalgorithms.com/

### CODE REVIEW

**Comment by tearodactyl** [comment]
My apologies, somehow it's been rather taxing to get these relatively simple changes in.

Of course, we did not touch travis.yaml, and the change that got picked up came from https://github.com/bisq-network/bisq-assets/pull/11

Our original commit only has the three files in question https://github.com/tearodactyl/bisq-assets/commit/21d2b6e2ef5f03b8e718273046219921e1c5ea5e

I loath the idea of redoing all the steps yet again, but perhaps you could give me a suggestion how to submit the correct commit listed above. Thanks!

**Comment by blabno** [comment]
Rebase against master and make sure that `.travis.yml` is not included in the PR.

**Comment by cbeams** [comment]
@tearodactyl, I will close this PR soon if the requested changes are not made.

**Comment by tearodactyl** [comment]
Chris, I understand your concern, but I'm at my wits end here.  Having made three attempts to construct the pull request just right, I'm no longer confident in being able to do this.  The original code changes took me maybe three hours, but getting them into the codebase already took at least three times that.

Not a noob at git or Github, I'm administering the Zero organization with a dozen repos and five contributors. Plus two more accounts, a personal public one and a commercial private one, that have perhaps another dozen repos and three contributors.

Kindly give us a little more time to figure this out, as somehow it has been rather non-trivial.
Thanks,
  Tearo

**Comment by blabno** [comment]
Closing due to no activity.

**Pull request closed without merging**
