### PR TITLE
Update Horizen (ZEN)

### PR DESCRIPTION
**Pull request by tarrenj**
- Official project URL: https://horizen.global/
- Official block explorer URL: https://explorer.horizen.global/

### CODE REVIEW

**Comment by tarrenj** [comment]
The Travis CI build fails at `./gradlew check`, but both `check` and `build` work fine for me:

```smrtz@smrtz-VirtualBox:~$ cd builds/bisq-assets/
smrtz@smrtz-VirtualBox:~/builds/bisq-assets$ ./gradlew check
Starting a Gradle Daemon (subsequent builds will be faster)

BUILD SUCCESSFUL in 11s
4 actionable tasks: 4 up-to-date
smrtz@smrtz-VirtualBox:~/builds/bisq-assets$ ./gradlew build

BUILD SUCCESSFUL in 0s
7 actionable tasks: 7 up-to-date
```

Can I get some more info on the error so I can fix please?

**Comment by cbeams** [comment]
@ManfredKarrer, this PR changes the name of this asset from ZenCash => Horizen, but leaves the ticker symbol the same (ZEN). Is this a compatible change?

@tarrenj, the reason the build is failing is that the name of the file must be the same as the name of the class. So please rename `src/test/java/bisq/asset/coins/Horizen.java` => `src/test/java/bisq/asset/coins/HorizenTest.java`

**Comment by tarrenj** [comment]
@cbeams Whoops! Fixed that, but I I forgot to push... Fixed now.

Regarding the ticker symbol, our ticker is remaining as ZEN, so that's intentional. Hopefully it's compatible with everything?

**Comment by cbeams** [comment]
Great, @tarrenj. Let's see what @ManfredKarrer has to say about compatibility of the name change and we'll go from there.

**Comment by ManfredKarrer** [comment]
@cbeams Yes the name change should not cause issues. Only symbol name changes could cause problems.

**Comment by tarrenj** [comment]
@ManfredKarrer Great, thanks!  What's the next step for us?

**Comment by cbeams** [comment]
This repository has been moved into the 'assets' directory of the https://github.com/bisq-network/bisq repository. Please resubmit this pull request against that repository. See https://github.com/bisq-network/bisq-docs/pull/84 for updated instructions. When submitting your pull request, please mention in the description (a) that this is a resubmission, (b) paste a link back to this original pull request, and (c) whether the original had already bee ACKed. Thank you.

**Pull request closed without merging**
