### PR TITLE
List ParsiCoin (PARS)

### PR DESCRIPTION
**Pull request by ParsiCoin**
Official project URL: https://parsicoin.net
Official block explorer URL: http://explorer.parsicoin.net

### CODE REVIEW

**Review by blabno — CHANGES_REQUESTED** [review]
NACK squash those commits

**Comment by blabno** [comment]
@cbeams 
1) this is privacy coin
2) commit history shows that tests were run and debugged on Travis
3) regex looks silly like no validation at all

**Comment by cbeams** [comment]
@ParsiCoin, please explain how a Bisq arbitrator would verify that a payment occurred. If this is not possible, then we cannot list your asset.

**Comment by ParsiCoin** [comment]
ParsiCoin is CryptoNote based users can't see wallet addresses, they should copy their transaction hash from their wallet and search it on blockchain explorer. they also can generate payment ids when they are going to request payments on their wallets.

**Comment by cbeams** [comment]
This repository has been moved into the 'assets' directory of the https://github.com/bisq-network/bisq repository. Please resubmit this pull request against that repository. See https://github.com/bisq-network/bisq-docs/pull/84 for updated instructions. When submitting your pull request, please mention in the description (a) that this is a resubmission, (b) paste a link back to this original pull request, and (c) whether the original had already bee ACKed. Thank you.

**Pull request closed without merging**
