### PR TITLE
List TurtleCoin (TRTL)

### PR DESCRIPTION
**Pull request by RocksteadyTC**
Official project URL: https://turtlecoin.lol
Official block explorer URL: https://turtle.land
Additional: TRTL wallets support transaction keys that enable 3rd party audits in case of a dispute similar to Monero

### CODE REVIEW

**Review by blabno — APPROVED** [review]
ACK

**Comment by rashedmyt** [comment]
@RocksteadyTC how about adding support for integrated address also.. whenever the turtlecoin software with integrated address would go live, the exchange could just start using them.

**Comment by RocksteadyTC** [comment]
Integrated addresses are live

**Comment by cbeams** [comment]
This repository has been moved into the 'assets' directory of the https://github.com/bisq-network/bisq repository. Please resubmit this pull request against that repository. See https://github.com/bisq-network/bisq-docs/pull/84 for updated instructions. When submitting your pull request, please mention in the description (a) that this is a resubmission, (b) paste a link back to this original pull request, and (c) whether the original had already bee ACKed. Thank you.

**Pull request closed without merging**
