### PR TITLE
List Starwels (MAI)

### PR DESCRIPTION
**Pull request by ghost**
Official project URL: https://www.zerogate.tk/139H5wy8H3tgXwJ33mXpwmm4oCfjKUo7dY/
Official block explorer URL: http://91.240.86.126:3001/

### CODE REVIEW

**Review by blabno — COMMENTED** [review]
web page is empty, explorer does not have domain

**Comment by ghost** [comment]
@blabno Can you add without a domain?

**Comment by blabno** [comment]
That's a question to @cbeams

**Review by cbeams — APPROVED** [review]
ACK. We don't have any rules that the website / explorer must have a domain. The website is bare bones, but it is clearly about / for this asset, so it's fine by me.

**Comment by cbeams** [comment]
This repository has been moved into the 'assets' directory of the https://github.com/bisq-network/bisq repository. Please resubmit this pull request against that repository. See https://github.com/bisq-network/bisq-docs/pull/84 for updated instructions. When submitting your pull request, please mention in the description (a) that this is a resubmission, (b) paste a link back to this original pull request, and (c) whether the original had already bee ACKed. Thank you.

**Pull request closed without merging**
