### PR TITLE
List BitCloud (BTDX)

### PR DESCRIPTION
**Pull request by dalijolijo**
- Official project URL: https://bit-cloud.info
- Official block explorer URL: https://chainz.cryptoid.info/btdx

### CODE REVIEW

**Comment by blabno** [comment]
Applied Bisq codestyle. Please squash those commits.

**Comment by blabno** [comment]
`git rebase -i HEAD^^`
Then in the editor you change `pick` to `fixup` on the commits you want to merge with upper commit.

**Comment by dalijolijo** [comment]
squash commits done

**Comment by cbeams** [comment]
Hey @blabno, just a heads up that there's no need to have submitters squash commits if the only "extra commits" in question are review commits, e.g. the one here in which you applied Bisq's code style. It's actually useful to preserve such commits because it teaches others what the style deviation was.

What's _not_ useful is having N partial commits that put together the original pull request. We always those three changes (`Asset` implementation, test and registration) to be atomic, and thus squashed if necessary. Thanks.

**Comment by dalijolijo** [comment]
What should I do now?

**Pull request merged**
